name: Deploy with Preloaded DB Volume

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Run with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Cleanup
      if: always()
      run: docker-compose down
